name: sdps-net  # Replace with your preferred environment name

channels:
  - pytorch  # Add the PyTorch channel for the specified versions

dependencies:
  - python=3.7
  - pytorch=1.10
  - torchvision
  - numpy
  - scipy
  - scikit-image
